In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import joblib

In [2]:
data = pd.read_csv('cancer_knn_dataset.csv')
data.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null    float64
 15  compactness error        569 non-null    float64
 16  concavity error          569 non-null    float64
 17  concave points error     569 non-null    float64
 18  symmetry error           569 non-null    float64
 19  fractal dimension error  569 non-null    float64
 20  worst radius             569 non-null    float64
 21  worst texture            569 non-null    float64
 22  worst perimeter          569 non-null    float64
 23  worst area               569 non-null    float64
 24  worst smoothness         569 non-null    float64
 25  worst compactness        569 non-null    float64
 26  worst concavity          569 non-null    float64
 27  worst concave points     569 non-null    float64
 28  worst symmetry           569 non-null    float64
 29  worst fractal dimension  569 non-null    float64
 30  target                   569 non-null    int64
dtypes: float64(30), int64(1)
memory usage: 137.9 KB

In [7]:
X= data.drop('target', axis=1)
y= data['target']

In [8]:
#Step 3: Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [9]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(455, 30)
(455,)
(114, 30)
(114,)

In [11]:
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
X_train_scaled[0:5]

array([[0.06552721, 0.25769361, 0.07732252, 0.03436883, 0.48722578,
        0.41750565, 0.73336457, 0.21744533, 0.50400427, 0.64237574,
        0.07818215, 0.18427334, 0.05314988, 0.02029892, 0.26637658,
        0.62943491, 0.76717172, 0.62928585, 0.63623129, 0.29933115,
        0.05964476, 0.28331557, 0.05597072, 0.02508436, 0.523195  ,
        0.44938009, 1.        , 0.60137457, 0.52493594, 0.52950153],
       [0.65620256, 0.57017247, 0.67420686, 0.48940187, 0.55493365,
        0.90343127, 0.58270853, 0.74353877, 0.65563267, 0.50589722,
        0.18768785, 0.08899841, 0.17231306, 0.13944393, 0.08634463,
        0.34050831, 0.09777778, 0.29683652, 0.18847288, 0.1520183 ,
        0.65791974, 0.57196162, 0.62025316, 0.46283247, 0.52930789,
        0.80287939, 0.54153355, 0.9975945 , 0.49931007, 0.62190573],
       [0.07257946, 0.14034494, 0.08023901, 0.0388312 , 0.22190124,
        0.23330594, 0.14029991, 0.1083499 , 0.62680192, 0.4142797 ,
        0.108021  , 0.42096888, 0.0872167 , 0.03122537, 0.23880749,
        0.2788476 , 0.10888889, 0.29551051, 0.63529807, 0.17022512,
        0.04868065, 0.19216418, 0.05642824, 0.02146189, 0.18467704,
        0.15430316, 0.11158147, 0.174811  , 0.33845851, 0.25313666],
       [0.14491405, 0.52451809, 0.14290795, 0.07577448, 0.3966778 ,
        0.18135744, 0.05574039, 0.08026839, 0.38974907, 0.28074979,
        0.05004527, 0.25035361, 0.03486783, 0.01837512, 0.18615087,
        0.06081954, 0.02729798, 0.11829892, 0.25566464, 0.05956773,
        0.13054601, 0.61753731, 0.11941437, 0.05758734, 0.53474156,
        0.12355454, 0.08985623, 0.21085911, 0.363493  , 0.224059  ],
       [0.12140653, 0.17483936, 0.11829563, 0.06071398, 0.54861425,
        0.20967742, 0.02539831, 0.06411531, 0.84143086, 0.41364785,
        0.14640594, 0.23886139, 0.12038826, 0.05195761, 0.1971989 ,
        0.06562622, 0.01935606, 0.15519985, 0.63361828, 0.17475091,
        0.08559316, 0.14472281, 0.07813533, 0.03597658, 0.38259866,
        0.07837603, 0.01731629, 0.08862543, 0.39266706, 0.21329264]])

In [13]:
X_test_scaled[0:5]

array([[0.23404672, 0.30064254, 0.23595106, 0.13365657, 0.42448316,
        0.29593863, 0.18755858, 0.18991054, 0.40469834, 0.29001685,
        0.10305993, 0.1511227 , 0.08198652, 0.04387017, 0.17812829,
        0.12661099, 0.06820707, 0.19643872, 0.18548658, 0.09297569,
        0.22995395, 0.33635394, 0.21127548, 0.11271834, 0.48515927,
        0.23117471, 0.21333866, 0.34879725, 0.2856298 , 0.27517803],
       [0.55090847, 0.39228948, 0.53834116, 0.41173947, 0.33817821,
        0.28600781, 0.25304592, 0.39517893, 0.22156967, 0.09793597,
        0.24526525, 0.09664516, 0.22282429, 0.16669468, 0.09283747,
        0.10715895, 0.05729798, 0.25951885, 0.11157565, 0.02774899,
        0.59140414, 0.3880597 , 0.56636673, 0.40750298, 0.32690348,
        0.22656241, 0.21461661, 0.61477663, 0.19436231, 0.09198033],
       [0.38047897, 0.33040243, 0.38255797, 0.24821934, 0.51069784,
        0.35244161, 0.34348641, 0.40193837, 0.40790176, 0.168492  ,
        0.13137787, 0.09408151, 0.11011638, 0.07752737, 0.15389061,
        0.09454141, 0.07103535, 0.20704679, 0.11362873, 0.05410914,
        0.38674074, 0.37260128, 0.35793808, 0.2313418 , 0.5666644 ,
        0.23293177, 0.30279553, 0.52027491, 0.25073921, 0.21320787],
       [0.23061854, 0.26952993, 0.23865415, 0.12760662, 0.47639253,
        0.38428875, 0.18137301, 0.13911531, 0.34383342, 0.44355518,
        0.02361036, 0.24306047, 0.06818075, 0.01611511, 0.28170786,
        0.23055547, 0.12275253, 0.2210646 , 0.26107731, 0.17654741,
        0.15357065, 0.2902452 , 0.17853693, 0.07249901, 0.5014603 ,
        0.25873865, 0.19193291, 0.2532646 , 0.19534792, 0.3268057 ],
       [0.18850091, 0.15995942, 0.19014085, 0.09975972, 0.42619843,
        0.31717006, 0.15784911, 0.12892644, 0.34757074, 0.37615838,
        0.06043817, 0.31112977, 0.04104038, 0.0262571 , 0.35479485,
        0.29191576, 0.14022727, 0.28300815, 0.19631192, 0.15951522,
        0.13091148, 0.20415778, 0.12348127, 0.05810838, 0.43014331,
        0.20262242, 0.14353035, 0.23773196, 0.15060122, 0.22295693]])

In [14]:
#Step 5: Train KNN Model
knn = KNeighborsClassifier(
    n_neighbors=5,
    metric='minkowski',
    p=3
)

In [15]:
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier(p=3)

In [16]:
#Step 6: Evaluate Model Accuracy
y_pred = knn.predict(X_test_scaled)

In [17]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy * 100)

Accuracy: 95.6140350877193

In [18]:
pd.crosstab(y_pred,y_test)

target   0   1
row_0
0       41   3
1        2  68

In [19]:
#create a classification report for categorical data
from sklearn.metrics import classification_report
cr = classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.93      0.95      0.94        43
           1       0.97      0.96      0.96        71

    accuracy                           0.96       114
   macro avg       0.95      0.96      0.95       114
weighted avg       0.96      0.96      0.96       114

In [20]:
#Step 7: Save Model and Scaler
joblib.dump(knn, "knn_cancer_model.pkl")
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']